# Generated by Django 3.0.7 on 2020-09-07 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finalEncuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfilEnc', models.CharField(max_length=300)),
                ('resultado', models.CharField(max_length=300)),
                ('momento', models.DateTimeField(auto_now_add=True, null=True)),
                ('tiempo', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='juegoEmparejarAntonimos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=150)),
                ('antonimo_1', models.CharField(help_text='Introduzca un antonimo', max_length=150, null=True)),
                ('antonimo_2', models.CharField(blank=True, help_text='Introduzca un antonimo', max_length=150, null=True)),
                ('antonimo_3', models.CharField(blank=True, help_text='Introduzca un antonimo', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='juegoEmparejarSinonimos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=150)),
                ('sininimo_1', models.CharField(help_text='Introduzca un sinonimo', max_length=150, null=True)),
                ('sininimo_2', models.CharField(blank=True, help_text='Introduzca un sinonimo', max_length=150, null=True)),
                ('sininimo_3', models.CharField(blank=True, help_text='Introduzca un sinonimo', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='preguntanivel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300)),
                ('texto', models.CharField(default='Texto de lectura si procede', max_length=3000)),
                ('pregunta', models.CharField(max_length=3000)),
                ('opcion1', models.CharField(help_text='Introduzca la primera respuesta', max_length=300)),
                ('opcion2', models.CharField(help_text='Introduzca la segunda respuesta', max_length=300)),
                ('opcion3', models.CharField(blank=True, help_text='Introduzca la tercera respuesta', max_length=300, null=True)),
                ('opcion4', models.CharField(blank=True, help_text='Introduzca la cuarta respuesta', max_length=300, null=True)),
                ('respuesta_correcta', models.CharField(help_text='Introduzca la respuesta correcta', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='preguntanivel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300)),
                ('texto', models.CharField(default='Texto de lectura si procede', max_length=3000)),
                ('pregunta', models.CharField(max_length=3000)),
                ('opcion1', models.CharField(help_text='Introduzca la primera respuesta', max_length=300)),
                ('opcion2', models.CharField(help_text='Introduzca la segunda respuesta', max_length=300)),
                ('opcion3', models.CharField(blank=True, help_text='Introduzca la tercera respuesta', max_length=300, null=True)),
                ('opcion4', models.CharField(blank=True, help_text='Introduzca la cuarta respuesta', max_length=300, null=True)),
                ('respuesta_correcta', models.CharField(help_text='Introduzca la respuesta correcta', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='preguntanivel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300)),
                ('texto', models.CharField(default='Texto de lectura si procede', max_length=3000)),
                ('pregunta', models.CharField(max_length=3000)),
                ('opcion1', models.CharField(help_text='Introduzca la primera respuesta', max_length=300)),
                ('opcion2', models.CharField(help_text='Introduzca la segunda respuesta', max_length=300)),
                ('opcion3', models.CharField(blank=True, help_text='Introduzca la tercera respuesta', max_length=300, null=True)),
                ('opcion4', models.CharField(blank=True, help_text='Introduzca la cuarta respuesta', max_length=300, null=True)),
                ('respuesta_correcta', models.CharField(help_text='Introduzca la respuesta correcta', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='preguntanivel4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300)),
                ('texto', models.CharField(default='Texto de lectura si procede', max_length=3000)),
                ('pregunta', models.CharField(max_length=3000)),
                ('opcion1', models.CharField(help_text='Introduzca la primera respuesta', max_length=300)),
                ('opcion2', models.CharField(help_text='Introduzca la segunda respuesta', max_length=300)),
                ('opcion3', models.CharField(blank=True, help_text='Introduzca la tercera respuesta', max_length=300, null=True)),
                ('opcion4', models.CharField(blank=True, help_text='Introduzca la cuarta respuesta', max_length=300, null=True)),
                ('respuesta_correcta', models.CharField(help_text='Introduzca la respuesta correcta', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='preguntanivel5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300)),
                ('texto', models.CharField(default='Texto de lectura si procede', max_length=3000)),
                ('pregunta', models.CharField(max_length=3000)),
                ('opcion1', models.CharField(help_text='Introduzca la primera respuesta', max_length=300)),
                ('opcion2', models.CharField(help_text='Introduzca la segunda respuesta', max_length=300)),
                ('opcion3', models.CharField(blank=True, help_text='Introduzca la tercera respuesta', max_length=300, null=True)),
                ('opcion4', models.CharField(blank=True, help_text='Introduzca la cuarta respuesta', max_length=300, null=True)),
                ('respuesta_correcta', models.CharField(help_text='Introduzca la respuesta correcta', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='preguntas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único para la pregunta', primary_key=True, serialize=False)),
                ('nivel', models.CharField(blank=True, choices=[('Nivel1', 'Nivel1'), ('Nivel2', 'Nivel2'), ('Nivel3', 'Nivel3'), ('Nivel4', 'Nivel4'), ('Nivel5', 'Nivel5')], help_text='Seleccione el nivel de la pregunta', max_length=10, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Booleana', 'Booleana'), ('Clasica', 'Clasica'), ('Rellenar', 'Rellenar')], help_text='Seleccione el tipo de la pregunta', max_length=10, null=True)),
                ('texto', models.CharField(blank=True, default='Texto de lectura si procede', max_length=3000, null=True)),
                ('pregunta', models.CharField(default='Ponga la pregunta aquí', max_length=3000)),
                ('opcion1', models.CharField(help_text='Introduzca la primera respuesta', max_length=300)),
                ('opcion2', models.CharField(help_text='Introduzca la segunda respuesta', max_length=300)),
                ('opcion3', models.CharField(blank=True, help_text='Introduzca la tercera respuesta', max_length=300, null=True)),
                ('opcion4', models.CharField(blank=True, help_text='Introduzca la cuarta respuesta', max_length=300, null=True)),
                ('respuesta_correcta', models.CharField(blank=True, help_text='Introduzca la respuesta correcta', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único para el report', primary_key=True, serialize=False)),
                ('contador', models.IntegerField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEncuesta.finalEncuesta')),
                ('preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEncuesta.preguntas')),
            ],
        ),
    ]
