# Generated by Django 3.1.2 on 2020-10-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEncuesta', '0003_auto_20201001_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntanivel1',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Booleana', 'Booleana'), ('Clasica', 'Clasica'), ('Cloze', 'Cloze')], help_text='Seleccione el tipo de la pregunta', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preguntanivel2',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Booleana', 'Booleana'), ('Clasica', 'Clasica'), ('Cloze', 'Cloze')], help_text='Seleccione el tipo de la pregunta', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preguntanivel3',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Booleana', 'Booleana'), ('Clasica', 'Clasica'), ('Cloze', 'Cloze')], help_text='Seleccione el tipo de la pregunta', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preguntanivel4',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Booleana', 'Booleana'), ('Clasica', 'Clasica'), ('Cloze', 'Cloze')], help_text='Seleccione el tipo de la pregunta', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='preguntanivel5',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Booleana', 'Booleana'), ('Clasica', 'Clasica'), ('Cloze', 'Cloze')], help_text='Seleccione el tipo de la pregunta', max_length=10, null=True),
        ),
    ]
