# Generated by Django 3.1.2 on 2020-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEncuesta', '0005_auto_20201001_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUploadForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='')),
            ],
        ),
    ]
