# Generated by Django 3.1.2 on 2020-10-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEncuesta', '0006_csvuploadform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvUploadForm',
        ),
    ]
