# Generated by Django 3.1.2 on 2020-10-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEncuesta', '0007_delete_csvuploadform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='preguntanivel1',
        ),
        migrations.DeleteModel(
            name='preguntanivel2',
        ),
        migrations.DeleteModel(
            name='preguntanivel3',
        ),
        migrations.DeleteModel(
            name='preguntanivel4',
        ),
        migrations.DeleteModel(
            name='preguntanivel5',
        ),
    ]
