# Generated by Django 3.1.2 on 2020-10-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEncuesta', '0008_auto_20201008_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fallo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
