# Generated by Django 3.1.2 on 2020-10-10 11:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEncuesta', '0011_auto_20201008_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportPreguntas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único para el report', primary_key=True, serialize=False)),
                ('contador', models.IntegerField(blank=True, default=0, null=True)),
                ('fallos', models.IntegerField(blank=True, default=0, null=True)),
                ('preguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEncuesta.preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='reportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfilEnc', models.CharField(max_length=300)),
                ('sexo', models.CharField(max_length=10)),
                ('rango_edad', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=10)),
                ('rasgo_nacional', models.CharField(max_length=10)),
                ('com_autonoma_nacimiento', models.CharField(max_length=10)),
                ('com_autonoma_actual', models.CharField(max_length=10)),
                ('com_autonoma_actual_anyos', models.CharField(max_length=10)),
                ('sector_trabajo', models.CharField(max_length=10)),
                ('renta', models.CharField(max_length=10)),
                ('estudios', models.CharField(max_length=10)),
                ('cultura', models.CharField(max_length=10)),
                ('frecuencia_libros', models.CharField(max_length=10)),
                ('tipos_libros', models.CharField(max_length=10)),
                ('uso_internet', models.CharField(max_length=10)),
                ('horas_estudio', models.CharField(max_length=10)),
                ('compras_internet', models.CharField(max_length=10)),
                ('dni_electronico', models.CharField(max_length=10)),
                ('renta_online', models.CharField(max_length=10)),
                ('blogs', models.CharField(max_length=10)),
                ('ocio_internet', models.CharField(max_length=10)),
                ('horas_ocio', models.CharField(max_length=10)),
                ('pregunta1', models.BooleanField()),
                ('pregunta2', models.BooleanField()),
                ('pregunta3', models.BooleanField()),
                ('pregunta4', models.BooleanField()),
                ('pregunta5', models.BooleanField()),
                ('emparejar_sinonimos', models.IntegerField(blank=True, null=True)),
                ('emparejar_antonimos', models.IntegerField(blank=True, null=True)),
                ('palabras_mezcladas', models.IntegerField(blank=True, null=True)),
                ('momento', models.DateTimeField(auto_now_add=True, null=True)),
                ('tiempo', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='report',
            name='preguntas',
        ),
        migrations.DeleteModel(
            name='finalEncuesta',
        ),
        migrations.DeleteModel(
            name='report',
        ),
    ]
