# Generated by Django 3.1.2 on 2020-11-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEncuesta', '0012_auto_20201010_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportuser',
            name='perfilEnc',
        ),
    ]
