# Generated by Django 3.1.2 on 2020-11-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEncuesta', '0014_auto_20201104_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportuser',
            name='frecuencia_libros',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='ocio_internet',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='tipos_libros',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reportuser',
            name='uso_internet',
            field=models.CharField(max_length=300),
        ),
    ]
